executable = runPG.sh
arguments  = $(ClusterID) $(ProcId)
output     = output/runPG.$(ClusterId).$(ProcId).out
error      = error/runPG.$(ClusterId).$(ProcId).err
log        = log/runPG.$(ClusterId).log
getenv = False
notification = Never
RequestCpus  = 1
should_transfer_files = NO
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)
max_retries    = 3

+JobFlavour  = "tomorrow"
+AccountingGroup = "group_u_SNDLHC.users"
requirements = Machine =!= LastRemoteHost
queue 100
